default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        files: \.ya?ml$
      - id: check-json
        files: \.json$
        exclude: ^aodn_cloud_optimised/config/dataset/dataset_template.json$
      - id: end-of-file-fixer
        exclude: '\.schema$'
      - id: trailing-whitespace
      - id: check-toml
      - id: pretty-format-json
        files: \.json$
        args: ["--autofix", "--no-sort-keys"]
        exclude: ^aodn_cloud_optimised/config/dataset/dataset_template.json$

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-jsonschema
        files: ^aodn_cloud_optimised/config/dataset/.*\.json$
        exclude: ^aodn_cloud_optimised/config/dataset/dataset_template.json$
        args:
          [
            "--schemafile",
            "aodn_cloud_optimised/config/schema_validation_common.json",
          ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        #exclude: ^aodn_cloud_optimised/bin/create_aws_registry_dataset.py$  # issue with black!

  - repo: https://github.com/python-poetry/poetry
    rev: "2.0.1"
    hooks:
      - id: poetry-check
        args: ["--lock", "--quiet"] # Add --quiet to run poetry-check quietly
        verbose: false
      # - id: poetry-export
      # args: ["-f", "requirements.txt", "--quiet"]
      # verbose: false
      - id: poetry-lock
        args: []
        verbose: true
      - id: poetry-install
        args: ["--quiet"]

  - repo: local
    hooks:
      - id: validate-json-configs
        name: Validate dataset JSON configs with Pydantic
        entry: python3 aodn_cloud_optimised/bin/pydantic_precommit_hook.py --validate-configs aodn_cloud_optimised/config/dataset
        language: system
        types: [json]
        pass_filenames: false
        always_run: true
