default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        files: \.ya?ml$
      - id: check-json
        files: \.json$
        exclude: ^aodn_cloud_optimised/config/dataset/dataset_template.json$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-export
        args: ["-f", "requirements.txt"]
        verbose: true
      - id: poetry-check
        args: ["--lock"]
        verbose: true
      - id: poetry-lock
      - id: poetry-install
