# Usage:
# export AWS_PROFILE=nonproduction-admin && mamba env create --file=environment.yml
# export AWS_PROFILE=nonproduction-admin && mamba env update --file=environment.yml

name: AodnCloudOptimised
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - notebook
  - h5py
  - scipy
  - pip<24.1
  - pip:
    - poetry
    - -r requirements.txt
