# Usage:
# export AWS_PROFILE=nonproduction-admin && mamba env create --file=environment.yml
# export AWS_PROFILE=nonproduction-admin && mamba env update --file=environment.yml

name: AodnCloudOptimised
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10.14,<3.13
  - notebook
  - h5py
  - scipy
  - pip<24.1
  - virtualenv==20.28.1 # https://github.com/python-poetry/poetry/issues/10056#issuecomment-2594269592
  - pip:
      - poetry==2.0.1
      - -r requirements.txt
