# Usage:
# export AWS_PROFILE=nonproduction-admin && conda env create --file=environment.yml
# export AWS_PROFILE=nonproduction-admin && conda env update --file=environment.yml

name: AodnCloudOptimised
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - notebook
  - h5py
  - scipy
  - pip
  - pip:
    - netCDF4>=1.6.5
    - numpy>=1.26.4
    - pandas>=2.2.2
    - python-dateutil>=2.9.0
    - jsonschema>=4.22.0
    - h5py>=3.11.0
    - scipy>=1.13.0
    - boto3>=1.34.100
    - pyarrow==16.0.0
    - rechunker>=0.5.2
    - s3fs>=2024.3.1
    - shapely>=2.0.4
    - xarray[complete]>=2024.3.0
    - zarr>=2.18.0
