name: Pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.14"

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pip install pydantic

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          version: 2.0.1

      - name: Clear Poetry Cache
        run: |
          poetry cache clear pypi --all

      - name: Install project - needed for custom poetry hook
        run: poetry install --no-interaction

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
