name: Pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
