name: mamba environment testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Miniconda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          generate-run-shell: true
          init-shell: bash

      - name: Activate Conda environment
        shell: bash -el {0}
        run: |
          poetry install --no-interaction

      - name: Run pytest and coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=60
          coverage xml -o coverage.xml

      #      - name: Upload coverage report
      #uses: actions/upload-artifact@v2
      #with:
      #name: coverage-report
      #          path: coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          path: coverage.xml
