name: aodn_cloud_optimised package build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'

      - name: Install package dependencies
        run: |
          pip install .

      - name: Install additional dependencies
        run: |
          pip install pytest coverage

      - name: Run setup.py install
        run: |
          python setup.py install

      - name: Run tests with coverage
        run: |
          pytest
          coverage run -m pytest
          coverage report --fail-under=60
          coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

